-- ============================================================================
-- 10_staging.sql
--
-- Landing zone: a structural 1:1 port of the Northwind OLTP schema.
-- Run after 00_schemas.sql.
--
-- Source of truth: sqlserver/database/northwind/northwind.sql
-- Every table, column, order and nullability below matches that file. Names are
-- converted to snake_case; nothing is added, removed or reordered.
--
-- ----------------------------------------------------------------------------
-- Type mapping applied throughout (see docs/migration-guide.md)
-- ----------------------------------------------------------------------------
--   nvarchar(n)          ->  varchar(n)
--   nchar(n)             ->  char(n)
--   ntext                ->  text
--   image                ->  bytea
--   money                ->  numeric(19,4)     -- not PG `money`: that type is
--                                              -- locale-dependent and its
--                                              -- output changes with lc_monetary
--   bit                  ->  boolean
--   real                 ->  real              -- preserved; tightened in warehouse
--   datetime             ->  timestamp(3)      -- source carries no time zone
--   smallint             ->  smallint
--   int IDENTITY(1,1)    ->  integer GENERATED BY DEFAULT AS IDENTITY
--
-- Why BY DEFAULT and not ALWAYS in this layer: staging is loaded with the
-- source system's own key values. GENERATED ALWAYS rejects an explicit insert
-- unless every statement carries OVERRIDING SYSTEM VALUE. BY DEFAULT accepts
-- the source key and still generates one if omitted. The trade-off is that the
-- underlying sequence is not advanced by explicit inserts, so the seed scripts
-- in postgres/seed/ reset it with setval() after loading. Warehouse surrogate
-- keys use GENERATED ALWAYS, where nothing outside ETL may supply a value.
--
-- ----------------------------------------------------------------------------
-- Constraint policy in this layer
-- ----------------------------------------------------------------------------
-- Primary keys are kept: they are the declared grain of each source table, and
-- a duplicate arriving here is a genuine extract failure worth stopping on.
--
-- Foreign keys and CHECK constraints are deliberately NOT carried over. A
-- landing zone that rejects rows loses the very evidence needed to diagnose an
-- upstream problem. Referential integrity and domain rules are asserted instead
-- by tests/validation.sql, which reports violations as data rather than
-- aborting the load.
-- ============================================================================

SET search_path = staging, public;

DROP TABLE IF EXISTS staging.order_details          CASCADE;
DROP TABLE IF EXISTS staging.orders                 CASCADE;
DROP TABLE IF EXISTS staging.products               CASCADE;
DROP TABLE IF EXISTS staging.categories             CASCADE;
DROP TABLE IF EXISTS staging.suppliers              CASCADE;
DROP TABLE IF EXISTS staging.shippers               CASCADE;
DROP TABLE IF EXISTS staging.customer_customer_demo CASCADE;
DROP TABLE IF EXISTS staging.customer_demographics  CASCADE;
DROP TABLE IF EXISTS staging.customers              CASCADE;
DROP TABLE IF EXISTS staging.employee_territories   CASCADE;
DROP TABLE IF EXISTS staging.territories            CASCADE;
DROP TABLE IF EXISTS staging.region                 CASCADE;
DROP TABLE IF EXISTS staging.employees              CASCADE;

-- ----------------------------------------------------------------------------
-- staging.categories                                        source: Categories
-- ----------------------------------------------------------------------------
CREATE TABLE staging.categories (
    category_id     integer       GENERATED BY DEFAULT AS IDENTITY,
    category_name   varchar(15)   NOT NULL,
    description     text          NULL,
    picture         bytea         NULL,

    CONSTRAINT pk_categories PRIMARY KEY (category_id)
);

COMMENT ON TABLE staging.categories IS 'Port of dbo.Categories.';

-- ----------------------------------------------------------------------------
-- staging.customers                                          source: Customers
--
-- The natural key is a 5-character alphabetic code (e.g. 'ALFKI'), not an
-- integer. char(5) is retained rather than "improved" to varchar so that the
-- blank-padding semantics of the source are reproduced exactly.
-- ----------------------------------------------------------------------------
CREATE TABLE staging.customers (
    customer_id     char(5)       NOT NULL,
    company_name    varchar(40)   NOT NULL,
    contact_name    varchar(30)   NULL,
    contact_title   varchar(30)   NULL,
    address         varchar(60)   NULL,
    city            varchar(15)   NULL,
    region          varchar(15)   NULL,
    postal_code     varchar(10)   NULL,
    country         varchar(15)   NULL,
    phone           varchar(24)   NULL,
    fax             varchar(24)   NULL,

    CONSTRAINT pk_customers PRIMARY KEY (customer_id)
);

COMMENT ON TABLE staging.customers IS 'Port of dbo.Customers.';

-- ----------------------------------------------------------------------------
-- staging.employees                                          source: Employees
--
-- Self-referencing hierarchy via reports_to. The source also carries
-- CK_Birthdate CHECK (BirthDate < getdate()).
--
-- That constraint CANNOT be ported. PostgreSQL requires CHECK expressions to be
-- immutable, and CURRENT_TIMESTAMP is stable, not immutable:
--
--     ERROR:  cannot use column reference in DEFAULT expression
--     ERROR:  functions in check constraint must be marked IMMUTABLE
--
-- SQL Server permits it, at the cost of a constraint whose truth value changes
-- with the clock and is never re-verified on existing rows. The rule is
-- enforced in tests/validation.sql instead, where it belongs.
-- ----------------------------------------------------------------------------
CREATE TABLE staging.employees (
    employee_id       integer       GENERATED BY DEFAULT AS IDENTITY,
    last_name         varchar(20)   NOT NULL,
    first_name        varchar(10)   NOT NULL,
    title             varchar(30)   NULL,
    title_of_courtesy varchar(25)   NULL,
    birth_date        timestamp(3)  NULL,
    hire_date         timestamp(3)  NULL,
    address           varchar(60)   NULL,
    city              varchar(15)   NULL,
    region            varchar(15)   NULL,
    postal_code       varchar(10)   NULL,
    country           varchar(15)   NULL,
    home_phone        varchar(24)   NULL,
    extension         varchar(4)    NULL,
    photo             bytea         NULL,
    notes             text          NULL,
    reports_to        integer       NULL,
    photo_path        varchar(255)  NULL,

    CONSTRAINT pk_employees PRIMARY KEY (employee_id)
);

COMMENT ON TABLE staging.employees IS
    'Port of dbo.Employees. CK_Birthdate is not portable (non-immutable '
    'expression) and is asserted in tests/validation.sql instead.';

-- ----------------------------------------------------------------------------
-- staging.shippers                                            source: Shippers
-- ----------------------------------------------------------------------------
CREATE TABLE staging.shippers (
    shipper_id      integer       GENERATED BY DEFAULT AS IDENTITY,
    company_name    varchar(40)   NOT NULL,
    phone           varchar(24)   NULL,

    CONSTRAINT pk_shippers PRIMARY KEY (shipper_id)
);

COMMENT ON TABLE staging.shippers IS 'Port of dbo.Shippers.';

-- ----------------------------------------------------------------------------
-- staging.suppliers                                          source: Suppliers
-- ----------------------------------------------------------------------------
CREATE TABLE staging.suppliers (
    supplier_id     integer       GENERATED BY DEFAULT AS IDENTITY,
    company_name    varchar(40)   NOT NULL,
    contact_name    varchar(30)   NULL,
    contact_title   varchar(30)   NULL,
    address         varchar(60)   NULL,
    city            varchar(15)   NULL,
    region          varchar(15)   NULL,
    postal_code     varchar(10)   NULL,
    country         varchar(15)   NULL,
    phone           varchar(24)   NULL,
    fax             varchar(24)   NULL,
    home_page       text          NULL,

    CONSTRAINT pk_suppliers PRIMARY KEY (supplier_id)
);

COMMENT ON TABLE staging.suppliers IS 'Port of dbo.Suppliers.';

-- ----------------------------------------------------------------------------
-- staging.products                                            source: Products
--
-- Source CHECK constraints (UnitPrice >= 0, UnitsInStock >= 0, UnitsOnOrder >= 0,
-- ReorderLevel >= 0) are portable verbatim but are held back to the warehouse
-- layer per the constraint policy above.
-- ----------------------------------------------------------------------------
CREATE TABLE staging.products (
    product_id        integer        GENERATED BY DEFAULT AS IDENTITY,
    product_name      varchar(40)    NOT NULL,
    supplier_id       integer        NULL,
    category_id       integer        NULL,
    quantity_per_unit varchar(20)    NULL,
    unit_price        numeric(19,4)  NULL DEFAULT 0,
    units_in_stock    smallint       NULL DEFAULT 0,
    units_on_order    smallint       NULL DEFAULT 0,
    reorder_level     smallint       NULL DEFAULT 0,
    discontinued      boolean        NOT NULL DEFAULT false,

    CONSTRAINT pk_products PRIMARY KEY (product_id)
);

COMMENT ON TABLE staging.products IS 'Port of dbo.Products.';
COMMENT ON COLUMN staging.products.discontinued IS
    'bit -> boolean. Source stores 0/1; the seed scripts cast on load.';

-- ----------------------------------------------------------------------------
-- staging.orders                                                source: Orders
-- ----------------------------------------------------------------------------
CREATE TABLE staging.orders (
    order_id          integer        GENERATED BY DEFAULT AS IDENTITY,
    customer_id       char(5)        NULL,
    employee_id       integer        NULL,
    order_date        timestamp(3)   NULL,
    required_date     timestamp(3)   NULL,
    shipped_date      timestamp(3)   NULL,
    ship_via          integer        NULL,
    freight           numeric(19,4)  NULL DEFAULT 0,
    ship_name         varchar(40)    NULL,
    ship_address      varchar(60)    NULL,
    ship_city         varchar(15)    NULL,
    ship_region       varchar(15)    NULL,
    ship_postal_code  varchar(10)    NULL,
    ship_country      varchar(15)    NULL,

    CONSTRAINT pk_orders PRIMARY KEY (order_id)
);

COMMENT ON TABLE staging.orders IS 'Port of dbo.Orders.';

-- ----------------------------------------------------------------------------
-- staging.order_details                                 source: Order Details
--
-- The source table name contains a space and is referenced throughout the
-- reference implementation as [Order Details]. The port renames it to
-- order_details: snake_case removes the need for quoted identifiers entirely,
-- which is the single most common cause of breakage when T-SQL is moved to a
-- case-sensitive-when-quoted engine.
-- ----------------------------------------------------------------------------
CREATE TABLE staging.order_details (
    order_id     integer        NOT NULL,
    product_id   integer        NOT NULL,
    unit_price   numeric(19,4)  NOT NULL DEFAULT 0,
    quantity     smallint       NOT NULL DEFAULT 1,
    discount     real           NOT NULL DEFAULT 0,

    CONSTRAINT pk_order_details PRIMARY KEY (order_id, product_id)
);

COMMENT ON TABLE staging.order_details IS
    'Port of [dbo].[Order Details]. Grain: one row per product per order.';

-- ----------------------------------------------------------------------------
-- staging.region                                                source: Region
-- ----------------------------------------------------------------------------
CREATE TABLE staging.region (
    region_id          integer     NOT NULL,
    region_description char(50)    NOT NULL,

    CONSTRAINT pk_region PRIMARY KEY (region_id)
);

COMMENT ON TABLE staging.region IS
    'Port of dbo.Region. No identity in the source - keys are supplied.';

-- ----------------------------------------------------------------------------
-- staging.territories                                      source: Territories
-- ----------------------------------------------------------------------------
CREATE TABLE staging.territories (
    territory_id          varchar(20)  NOT NULL,
    territory_description char(50)     NOT NULL,
    region_id             integer      NOT NULL,

    CONSTRAINT pk_territories PRIMARY KEY (territory_id)
);

COMMENT ON TABLE staging.territories IS 'Port of dbo.Territories.';

-- ----------------------------------------------------------------------------
-- staging.employee_territories                     source: EmployeeTerritories
-- ----------------------------------------------------------------------------
CREATE TABLE staging.employee_territories (
    employee_id   integer      NOT NULL,
    territory_id  varchar(20)  NOT NULL,

    CONSTRAINT pk_employee_territories PRIMARY KEY (employee_id, territory_id)
);

COMMENT ON TABLE staging.employee_territories IS
    'Port of dbo.EmployeeTerritories. Bridge: employees to territories, m:n.';

-- ----------------------------------------------------------------------------
-- staging.customer_demographics                   source: CustomerDemographics
-- ----------------------------------------------------------------------------
CREATE TABLE staging.customer_demographics (
    customer_type_id  char(10)  NOT NULL,
    customer_desc     text      NULL,

    CONSTRAINT pk_customer_demographics PRIMARY KEY (customer_type_id)
);

COMMENT ON TABLE staging.customer_demographics IS
    'Port of dbo.CustomerDemographics. Empty in the source data.';

-- ----------------------------------------------------------------------------
-- staging.customer_customer_demo                 source: CustomerCustomerDemo
-- ----------------------------------------------------------------------------
CREATE TABLE staging.customer_customer_demo (
    customer_id       char(5)   NOT NULL,
    customer_type_id  char(10)  NOT NULL,

    CONSTRAINT pk_customer_customer_demo PRIMARY KEY (customer_id, customer_type_id)
);

COMMENT ON TABLE staging.customer_customer_demo IS
    'Port of dbo.CustomerCustomerDemo. Empty in the source data.';

-- ----------------------------------------------------------------------------
-- Extract-side indexes
--
-- The reference implementation carries 30 indexes, several of them exact
-- duplicates created under different names (CustomerID and CustomersOrders on
-- Orders(CustomerID); CategoryID and CategoriesProducts on Products(CategoryID);
-- and so on - eight duplicated pairs in total).
--
-- They are not reproduced. Staging is written once per load and read once per
-- load, in full-table passes; secondary indexes would slow the write and never
-- be used by the read. The duplicates are catalogued in docs/migration-guide.md
-- as a finding, not carried forward as a feature.
--
-- Only the extract-ordering index below earns its place: the dimension loaders
-- probe staging.orders by customer to build SCD2 change sets.
-- ----------------------------------------------------------------------------
CREATE INDEX ix_staging_orders_customer_date
    ON staging.orders (customer_id, order_date);
