-- ============================================================================
-- 20_dimensions.sql
--
-- Kimball conformed dimensions. Run after 10_staging.sql.
--
-- ----------------------------------------------------------------------------
-- Design decisions recorded here rather than in a wiki nobody reads
-- ----------------------------------------------------------------------------
--
-- 1. SURROGATE KEYS. Every dimension is keyed by a meaningless integer
--    generated by the warehouse (GENERATED ALWAYS AS IDENTITY - nothing outside
--    ETL may supply one). Natural keys are retained as attributes. This is what
--    makes SCD Type 2 possible at all: a fact row points at a *version* of a
--    customer, not at a customer.
--
-- 2. HIERARCHIES ARE COLLAPSED, NOT SNOWFLAKED. Category and supplier
--    attributes are denormalised into dim_product rather than kept as separate
--    dimension tables joined off it.
--
--    This deviates from the Phase 1 sketch, which proposed a separate SCD2
--    dim_supplier. Collapsing is the correct Kimball answer: product ->
--    category and product -> supplier are both many-to-one, so a separate table
--    buys nothing but an extra join on every query, while costing the ability
--    to browse category and supplier attributes in one pass. Storage saved by
--    normalising a 29-row supplier table is not a real number. "Sales by
--    supplier country" still works - the attribute simply lives on dim_product.
--
-- 3. VALIDITY IS A HALF-OPEN INTERVAL [valid_from, valid_to).
--    valid_to IS NULL means "still current". NULL rather than a 9999-12-31
--    sentinel because tstzrange(valid_from, NULL) yields a genuinely unbounded
--    range, letting the database enforce non-overlap declaratively (see 4), and
--    because `IS NULL` is immutable where a comparison against a cast literal
--    is not - which matters for generated columns.
--
-- 4. OVERLAPPING VERSIONS ARE IMPOSSIBLE, NOT MERELY UNLIKELY.
--    Each SCD2 dimension carries an EXCLUDE constraint pairing the natural key
--    (=) with the validity range (&&). Two overlapping versions of the same
--    business entity cannot be committed, whatever the loader does. SQL Server
--    has no declarative equivalent; the reference implementation would rely on
--    procedural discipline plus an audit query. Requires btree_gist (00_schemas).
--
-- 5. EVERY DIMENSION HAS AN UNKNOWN MEMBER at key -1, inserted below.
--    Facts referencing missing or unresolvable dimension rows point at -1 and
--    stay in the fact table. Early-arriving facts are therefore never dropped
--    and never orphaned, and the fact-to-dimension foreign keys can be trusted
--    absolutely - which is what lets tests/validation.sql treat any orphan as a
--    hard failure rather than an expected condition.
-- ============================================================================

SET search_path = warehouse, staging, public;

DROP TABLE IF EXISTS warehouse.dim_customer CASCADE;
DROP TABLE IF EXISTS warehouse.dim_product  CASCADE;
DROP TABLE IF EXISTS warehouse.dim_employee CASCADE;
DROP TABLE IF EXISTS warehouse.dim_shipper  CASCADE;
DROP TABLE IF EXISTS warehouse.dim_date     CASCADE;

-- ============================================================================
-- dim_date
--
-- Grain: one row per calendar day.
-- SCD:   not applicable - the calendar does not change.
-- Key:   a "smart" integer key, yyyymmdd. Deliberate exception to the
--        meaningless-surrogate rule: date keys are readable in raw fact data,
--        sort correctly, and allow a fact partition to be range-scanned on the
--        key alone without joining the dimension.
--
-- Role-playing: joined three times from the sales fact (order, required,
-- shipped). The role-playing views live in postgres/views/.
--
-- Fiscal calendar is UK-convention: fiscal year starts 1 April and is named for
-- the calendar year in which it ends (1 Apr 2024 -> FY2025).
-- ============================================================================
CREATE TABLE warehouse.dim_date (
    date_key              integer      NOT NULL,
    full_date             date         NULL,

    day_of_month          smallint     NULL,
    day_of_week           smallint     NULL,      -- ISO: 1 = Monday .. 7 = Sunday
    day_name              varchar(9)   NULL,
    day_of_year           smallint     NULL,

    week_of_year          smallint     NULL,      -- ISO 8601 week number
    iso_year              smallint     NULL,      -- ISO year; differs at year boundaries

    month_number          smallint     NULL,
    month_name            varchar(9)   NULL,
    month_abbrev          char(3)      NULL,
    month_end_date        date         NULL,
    year_month            integer      NULL,      -- yyyymm, for grouping and sorting

    quarter_number        smallint     NULL,
    quarter_name          char(2)      NULL,      -- Q1 .. Q4
    year_number           smallint     NULL,

    fiscal_year           smallint     NULL,
    fiscal_quarter        smallint     NULL,

    is_weekend            boolean      NULL,
    is_last_day_of_month  boolean      NULL,

    CONSTRAINT pk_dim_date PRIMARY KEY (date_key),

    -- Real dates must be fully populated; only the unknown member may be sparse.
    CONSTRAINT ck_dim_date_real_rows_populated
        CHECK (date_key < 0 OR full_date IS NOT NULL),

    -- The smart key must agree with the date it encodes. A silent mismatch here
    -- would misdirect every fact row loaded for that day.
    CONSTRAINT ck_dim_date_key_matches_date
        CHECK (
            date_key < 0
            OR date_key = (EXTRACT(YEAR  FROM full_date) * 10000
                         + EXTRACT(MONTH FROM full_date) * 100
                         + EXTRACT(DAY   FROM full_date))
        ),

    CONSTRAINT ck_dim_date_month  CHECK (month_number   IS NULL OR month_number   BETWEEN 1 AND 12),
    CONSTRAINT ck_dim_date_quarter CHECK (quarter_number IS NULL OR quarter_number BETWEEN 1 AND 4),
    CONSTRAINT ck_dim_date_dow    CHECK (day_of_week    IS NULL OR day_of_week    BETWEEN 1 AND 7)
);

COMMENT ON TABLE warehouse.dim_date IS
    'Grain: one calendar day. Smart key yyyymmdd. Role-played as order date, '
    'required date and shipped date by fact_sales_order_line.';

CREATE UNIQUE INDEX uix_dim_date_full_date ON warehouse.dim_date (full_date)
    WHERE full_date IS NOT NULL;
CREATE INDEX ix_dim_date_year_month ON warehouse.dim_date (year_month);

INSERT INTO warehouse.dim_date (date_key, day_name, month_name, quarter_name)
VALUES (-1, 'Unknown', 'Unknown', 'NA');

-- ============================================================================
-- dim_customer
--
-- Grain: one row per customer per version.
-- SCD:   Type 2 on the full attribute set.
--
-- Type 2 across every attribute is the right call for this dimension. A
-- customer's address, contact and title are exactly the attributes an analyst
-- slices historical revenue by, and restating three years of sales because a
-- contact changed job title is precisely the failure mode Type 2 exists to
-- prevent.
-- ============================================================================
CREATE TABLE warehouse.dim_customer (
    customer_key      integer       GENERATED ALWAYS AS IDENTITY,

    customer_id       char(5)       NOT NULL,      -- natural key
    company_name      varchar(40)   NOT NULL,
    contact_name      varchar(30)   NULL,
    contact_title     varchar(30)   NULL,
    address           varchar(60)   NULL,
    city              varchar(15)   NULL,
    region            varchar(15)   NULL,
    postal_code       varchar(10)   NULL,
    country           varchar(15)   NULL,
    phone             varchar(24)   NULL,
    fax               varchar(24)   NULL,

    -- SCD Type 2 control
    valid_from        timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_to          timestamptz   NULL,
    is_current        boolean       GENERATED ALWAYS AS (valid_to IS NULL) STORED,
    validity          tstzrange     GENERATED ALWAYS AS (tstzrange(valid_from, valid_to)) STORED,
    row_hash          text          NULL,          -- md5 of tracked attributes

    -- Lineage
    dw_load_batch_id  bigint        NULL,
    dw_inserted_at    timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dw_updated_at     timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_dim_customer PRIMARY KEY (customer_key),

    CONSTRAINT fk_dim_customer_batch
        FOREIGN KEY (dw_load_batch_id) REFERENCES etl.load_batch (load_batch_id),

    CONSTRAINT ck_dim_customer_validity
        CHECK (valid_to IS NULL OR valid_to > valid_from),

    -- No two versions of one customer may be valid at the same instant.
    CONSTRAINT ex_dim_customer_no_overlap
        EXCLUDE USING gist (customer_id WITH =, validity WITH &&)
);

COMMENT ON TABLE warehouse.dim_customer IS
    'Grain: one row per customer per version. SCD Type 2. valid_to IS NULL '
    'marks the current version.';

-- Exactly one current version per customer. The EXCLUDE constraint above stops
-- overlaps but would still permit two current rows if a loader wrote them with
-- identical valid_from; this closes that gap.
CREATE UNIQUE INDEX uix_dim_customer_current
    ON warehouse.dim_customer (customer_id) WHERE is_current;

CREATE INDEX ix_dim_customer_natural  ON warehouse.dim_customer (customer_id);
CREATE INDEX ix_dim_customer_country  ON warehouse.dim_customer (country) WHERE is_current;

INSERT INTO warehouse.dim_customer
    (customer_key, customer_id, company_name, contact_name, country, valid_from)
OVERRIDING SYSTEM VALUE
VALUES (-1, '?????', 'Unknown', 'Unknown', 'Unknown', '1900-01-01 00:00:00+00');

-- ============================================================================
-- dim_product
--
-- Grain: one row per product per version.
-- SCD:   Type 2 on descriptive and pricing attributes.
--        Type 1 on stock levels (see below).
--
-- Stock columns are Type 1 - overwritten in place, never versioned. They change
-- on every transaction, and versioning them would generate a new dimension row
-- per product per day for no analytical gain: a 77-row dimension would grow by
-- ~28,000 rows a year and every historical query would need a date-qualified
-- join to find "the" product. Inventory level is a fact measure, not a product
-- attribute; it belongs in a periodic snapshot fact if it is ever needed.
--
-- Category and supplier attributes are denormalised in (decision 2 above).
-- ============================================================================
CREATE TABLE warehouse.dim_product (
    product_key           integer       GENERATED ALWAYS AS IDENTITY,

    product_id            integer       NOT NULL,   -- natural key
    product_name          varchar(40)   NOT NULL,
    quantity_per_unit     varchar(20)   NULL,
    unit_price            numeric(19,4) NULL,
    discontinued          boolean       NOT NULL DEFAULT false,

    -- Collapsed category hierarchy
    category_id           integer       NULL,
    category_name         varchar(15)   NULL,
    category_description  text          NULL,

    -- Collapsed supplier hierarchy
    supplier_id           integer       NULL,
    supplier_name         varchar(40)   NULL,
    supplier_contact_name varchar(30)   NULL,
    supplier_city         varchar(15)   NULL,
    supplier_country      varchar(15)   NULL,

    -- Type 1 attributes: current state only, overwritten on every load
    units_in_stock        smallint      NULL,
    units_on_order        smallint      NULL,
    reorder_level         smallint      NULL,

    -- SCD Type 2 control
    valid_from            timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_to              timestamptz   NULL,
    is_current            boolean       GENERATED ALWAYS AS (valid_to IS NULL) STORED,
    validity              tstzrange     GENERATED ALWAYS AS (tstzrange(valid_from, valid_to)) STORED,
    row_hash              text          NULL,

    -- Lineage
    dw_load_batch_id      bigint        NULL,
    dw_inserted_at        timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dw_updated_at         timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_dim_product PRIMARY KEY (product_key),

    CONSTRAINT fk_dim_product_batch
        FOREIGN KEY (dw_load_batch_id) REFERENCES etl.load_batch (load_batch_id),

    CONSTRAINT ck_dim_product_validity
        CHECK (valid_to IS NULL OR valid_to > valid_from),

    -- Ported verbatim from the source CHECK constraints on dbo.Products.
    CONSTRAINT ck_dim_product_unit_price     CHECK (unit_price     IS NULL OR unit_price     >= 0),
    CONSTRAINT ck_dim_product_units_in_stock CHECK (units_in_stock IS NULL OR units_in_stock >= 0),
    CONSTRAINT ck_dim_product_units_on_order CHECK (units_on_order IS NULL OR units_on_order >= 0),
    CONSTRAINT ck_dim_product_reorder_level  CHECK (reorder_level  IS NULL OR reorder_level  >= 0),

    CONSTRAINT ex_dim_product_no_overlap
        EXCLUDE USING gist (product_id WITH =, validity WITH &&)
);

COMMENT ON TABLE warehouse.dim_product IS
    'Grain: one row per product per version. SCD Type 2 on descriptive and '
    'pricing attributes; Type 1 on stock levels. Category and supplier '
    'hierarchies collapsed in.';

CREATE UNIQUE INDEX uix_dim_product_current
    ON warehouse.dim_product (product_id) WHERE is_current;

CREATE INDEX ix_dim_product_natural  ON warehouse.dim_product (product_id);
CREATE INDEX ix_dim_product_category ON warehouse.dim_product (category_name) WHERE is_current;
CREATE INDEX ix_dim_product_supplier ON warehouse.dim_product (supplier_id)   WHERE is_current;

INSERT INTO warehouse.dim_product
    (product_key, product_id, product_name, category_name, supplier_name, valid_from)
OVERRIDING SYSTEM VALUE
VALUES (-1, -1, 'Unknown', 'Unknown', 'Unknown', '1900-01-01 00:00:00+00');

-- ============================================================================
-- dim_employee
--
-- Grain: one row per employee per version.
-- SCD:   Type 2.
--
-- The source hierarchy (Employees.ReportsTo -> Employees.EmployeeID) is
-- flattened to manager_employee_id / manager_name. Facts join to an employee,
-- not to a recursive CTE, and "sales by manager" costs no extra join.
--
-- photo (image/bytea) and notes are not carried forward: a warehouse dimension
-- is for slicing, and a 40 KB bitmap per row is dead weight in every scan.
-- photo_path is retained so an application can still resolve the image.
-- ============================================================================
CREATE TABLE warehouse.dim_employee (
    employee_key         integer       GENERATED ALWAYS AS IDENTITY,

    employee_id          integer       NOT NULL,   -- natural key
    first_name           varchar(10)   NOT NULL,
    last_name            varchar(20)   NOT NULL,
    full_name            varchar(31)   NULL,       -- first || ' ' || last, built by ETL
    title                varchar(30)   NULL,
    title_of_courtesy    varchar(25)   NULL,
    birth_date           date          NULL,
    hire_date            date          NULL,
    address              varchar(60)   NULL,
    city                 varchar(15)   NULL,
    region               varchar(15)   NULL,
    postal_code          varchar(10)   NULL,
    country              varchar(15)   NULL,
    home_phone           varchar(24)   NULL,
    extension            varchar(4)    NULL,
    photo_path           varchar(255)  NULL,

    -- Flattened reporting line
    manager_employee_id  integer       NULL,
    manager_name         varchar(31)   NULL,
    is_manager           boolean       NOT NULL DEFAULT false,

    -- SCD Type 2 control
    valid_from           timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid_to             timestamptz   NULL,
    is_current           boolean       GENERATED ALWAYS AS (valid_to IS NULL) STORED,
    validity             tstzrange     GENERATED ALWAYS AS (tstzrange(valid_from, valid_to)) STORED,
    row_hash             text          NULL,

    -- Lineage
    dw_load_batch_id     bigint        NULL,
    dw_inserted_at       timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dw_updated_at        timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_dim_employee PRIMARY KEY (employee_key),

    CONSTRAINT fk_dim_employee_batch
        FOREIGN KEY (dw_load_batch_id) REFERENCES etl.load_batch (load_batch_id),

    CONSTRAINT ck_dim_employee_validity
        CHECK (valid_to IS NULL OR valid_to > valid_from),

    -- Nobody manages themselves. The source permits it; the warehouse does not,
    -- because a self-referencing manager breaks org-chart rollups silently.
    CONSTRAINT ck_dim_employee_not_own_manager
        CHECK (manager_employee_id IS NULL OR manager_employee_id <> employee_id),

    CONSTRAINT ck_dim_employee_hired_after_birth
        CHECK (birth_date IS NULL OR hire_date IS NULL OR hire_date > birth_date),

    CONSTRAINT ex_dim_employee_no_overlap
        EXCLUDE USING gist (employee_id WITH =, validity WITH &&)
);

COMMENT ON TABLE warehouse.dim_employee IS
    'Grain: one row per employee per version. SCD Type 2. Reporting hierarchy '
    'flattened to manager_employee_id / manager_name.';

CREATE UNIQUE INDEX uix_dim_employee_current
    ON warehouse.dim_employee (employee_id) WHERE is_current;

CREATE INDEX ix_dim_employee_natural ON warehouse.dim_employee (employee_id);
CREATE INDEX ix_dim_employee_manager ON warehouse.dim_employee (manager_employee_id) WHERE is_current;

INSERT INTO warehouse.dim_employee
    (employee_key, employee_id, first_name, last_name, full_name, valid_from)
OVERRIDING SYSTEM VALUE
VALUES (-1, -1, 'Unknown', 'Unknown', 'Unknown', '1900-01-01 00:00:00+00');

-- ============================================================================
-- dim_shipper
--
-- Grain: one row per shipper.
-- SCD:   Type 1 - overwritten in place.
--
-- Three carriers whose only attributes are a name and a phone number. Nobody
-- will ever ask what a carrier's phone number was in 1997. Type 2 machinery
-- here would be ceremony without benefit; the point of documenting SCD strategy
-- per dimension is to be able to justify Type 1 where Type 1 is correct.
-- ============================================================================
CREATE TABLE warehouse.dim_shipper (
    shipper_key       integer       GENERATED ALWAYS AS IDENTITY,

    shipper_id        integer       NOT NULL,      -- natural key
    company_name      varchar(40)   NOT NULL,
    phone             varchar(24)   NULL,

    -- Lineage
    dw_load_batch_id  bigint        NULL,
    dw_inserted_at    timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dw_updated_at     timestamptz   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_dim_shipper PRIMARY KEY (shipper_key),

    CONSTRAINT fk_dim_shipper_batch
        FOREIGN KEY (dw_load_batch_id) REFERENCES etl.load_batch (load_batch_id),

    -- Type 1: the natural key is unique outright, with no validity dimension.
    CONSTRAINT uq_dim_shipper_natural UNIQUE (shipper_id)
);

COMMENT ON TABLE warehouse.dim_shipper IS
    'Grain: one row per shipper. SCD Type 1 - attributes overwritten in place.';

INSERT INTO warehouse.dim_shipper (shipper_key, shipper_id, company_name)
OVERRIDING SYSTEM VALUE
VALUES (-1, -1, 'Unknown');
